var skilltree = {
    "Admin":1,
    "Advocate":1,
    "Agriculture":1,
    "Animals":{"Farming":1,
    "Riding":1,
    "Survival":1,
    "Veterinary Medicine":1},
    "Brawling":1,
    "Farming":1,
    "Riding":1,
    "Survival":1,
    "Veterinary Medicine":1,
    "Athletics":1,
    "Gun Combat": {"Archery":1,
    "Energy Pistol":1,
    "Energy Rifle":1,
    "Shotgun":1,
    "Slug Pistol":1,
    "Slug Rifle":1},
    "Archery":1,
    "Energy Pistol":1,
    "Energy Rifle":1,
    "Shotgun":1,
    "Slug Pistol":1,
    "Slug Rifle":1,
    "Vehicle": {
        "Aircraft":{
            "Grav Vehicle":1,
            "Rotor Aircraft":1,
            "Winged Aircraft":1
        },
        "Ground Vehicle": {
            "Mole":1,
            "Tracked Vehicle":1,
            "Wheeled Vehicle":1
        },
        "Watercraft":{
            "Motorboats":1,
            "Ocean Ships":1,
            "Sailing Ships":1,
            "Submarine":1
        }
    },
    "Aircraft":{
        "Grav Vehicle":1,
        "Rotor Aircraft":1,
        "Winged Aircraft":1
    },
    "Ground Vehicle":{
        "Mole":1,
        "Tracked Vehicle":1,
        "Wheeled Vehicle":1
    },
    "Watercraft":{
        "Motorboats":1,
        "Ocean Ships":1,
        "Sailing Ships":1,
        "Submarine":1,
    },
    "Grav Vehicle":1,
    "Rotor Aircraft":1,
    "Winged Aircraft":1,
    "Mole":1,
    "Tracked Vehicle":1,
    "Wheeled Vehicle":1,
    "Motorboats":1,
    "Ocean Ships":1,
    "Sailing Ships":1,
    "Submarine":1,
    "Gunnery": {
        "Bay Weapons":1,
        "Heavy Weapons":1,
        "Screens":1,
        "Spinal Mounts":1,
        "Turret Weapons":1
    },
    "Bay Weapons":1,
    "Heavy Weapons":1,
    "Screens":1,
    "Spinal Mounts":1,
    "Turret Weapons":1,
    "Battle Dress":1,
    "Bribery":1,
    "Broker":1,
    "Carousing":1,
    "Comms":1,
    "Computer":1,
    "Melee Combat": {
        "Bludgeoning Weapons":1,
        "Natural Weapons":1,
        "Piercing Weapons":1,
        "Slashing Weapons":1
    },
    "Bludgeoning Weapons":1,
    "Natural Weapons":1,
    "Piercing Weapons":1,
    "Slashing Weapons":1,

    "Demolitions":1,
    "Electronics":1,
    "Engineering":1,
    "Gambling":1,
    "Gravitics":1,
    "Jack-of-All-Trades":1,
    "Investigate":1,
    "Leadership":1,
    "Linguistics":1,
    "Liaison":1,
    "Mechanics":1,
    "Medicine":1,
    "Navigation":1,
    "Piloting":1,
    "Recon":1,
    "Sciences":{"Life Sciences":1,
    "Physical Sciences":1,
    "Social Sciences":1,
    "Space Sciences":1},
    "Life Sciences":1,
    "Physical Sciences":1,
    "Social Sciences":1,
    "Space Sciences":1,
    "Steward":1,
    "Streetwise":1,
    "Tactics":1,
    "Zero-G":1,
    "Mining":1,
    "Forgery":1
    };
